baseURL = "http://example.org/" #por enquanto não usamos essa configuração
languageCode = "pt-br" #por enquanto não usamos essa configuração
title = "DevOpsDays São Paulo"
theme = "devopsdayspoa"
googleAnalytics = "UA-36355678-4" # Enable Google Analytics by entering your tracking id

[params]
description = "Evento da cultura DevOps que será realizado em São Paulo e discute desenvolvimento de software, infraestrutura e operações no contexto de tecnologia de informação. Também abrange tudo que fica na intersecção dessas duas áreas como processos, postura, comportamento entre outros." #irá preencher o meta description
slider = "enable" #qualquer coisa que não seja "enable" irá desabilitar o slider (as imagens que ficam correndo atrás do logo/nome do evento)
slider_selector = "disable" #qualquer coisa que não seja "enable" irá desabilitar os seletores
slider_sidecontrols = "enable" #qualquer coisa que não seja "enable" irá desabilitar os controles
# intro_image = "Gears.svg" #apenas o nome da imagem, deve estar em img/intro/
intro_image = "logo-dod-sampa-transp.svg" #apenas o nome da imagem, deve estar em img/intro/
# link_c4p = "https://www.papercall.io/devopsdays-sp-2018" #endereço para o form/sistema de call4papers

email = "organizers-sao-paulo-2018@devopsdays.org" #email da organização do email
twitter = "@sp_devopsdays" #para https://www.twitter.com/nao-existe colocar apenas "não-existe"
facebook = "nao-existe" #para https://www.facebook.com/nao-existe colocar apenas "não-existe"

#Os próximos 3 parametros aceitam tags html (ex: <br>) e markdown (ex: **negrito**)
quando = "6 e 7 de junho de 2018"
onde = "Hotel Century Paulista. Rua Teixeira da Silva, 637 / 647 - Paraíso - São Paulo"
quanto = "A partir de R$ 220,00"
onde_latitude = -23.5733971
onde_longitude = -46.6498165

#latitude e longitude podem ser pegos no google maps mesmo :)
#o mapa irá ficar centralizado nessas coordenadas E irá colocar o marcador exatamente sobre elas
mapa_latitude = -23.5733971
mapa_longitude = -46.6498165
mapa_zoom = 14 #nível de zoom que será apresentado o mapa
mapa_draggable = true #o mapa poderá ser arrastado?
mapa_zoomControl = true #mostrar o controle de zoom?
mapa_scrollwheel = false #a roda de rolagem do mouse deve poder alterar o zoom?
mapa_disableDoubleClickZoom = true #vou ser sincero, não entendi o que isso faz, hahaha
mapa_key = "AIzaSyCiPpI9Poabi4Utt9s8eVsYZfHTP_gFIKA" #chave na api do google, lembre de permitir o uso no google maps e afins!

status_ingressos = "disponiveis" #qualquer coisa que não seja "disponiveis" irá mostrar o aviso
aviso_status_ingressos = "Esgotados!"

status_programacao = "indisponivel" #qualquer coisa que não seja "disponivel" irá mostrar o aviso
aviso_status_programacao = "Em breve! ;s)"
